version: 0.2
env:
  parameter-store:
    DOCKER_USER: "/myapp/docker-credentials/username"
    DOCKER_PASS: "/myapp/docker-credentials/password"
phases:
  pre_build:
    commands:
      - echo "Logging into Docker"
      - echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
  build:
    commands:
      - docker build -t myapp:latest .
  post_build:
    commands:
      - docker tag myapp:latest $DOCKER_USER/myapp:latest
      - docker push $DOCKER_USER/myapp:latest
