version: 0.2
env:
  parameter-store:
    DOCKER_USERNAME: "/myapp/docker-credentials/username"
    DOCKER_PASSWORD: "/myapp/docker-credentials/password"

phases:
  pre_build:
    commands:
      - echo "Logging into Docker..."
      - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t myapp:latest .

  post_build:
    commands:
      - echo "Tagging image..."
      - docker tag myapp:latest $DOCKER_USERNAME/myapp:latest
      
      - echo "Pushing to DockerHub..."
      - docker push $DOCKER_USERNAME/myapp:latest
      
      - echo "Build completed successfully!"
