version: 0.2

phases:
  pre_build:
    commands:
      - echo "===== DEBUG INFO ====="
      - echo "USERNAME -> $DOCKER_REGISTRY_USERNAME"
      - echo "PASSWORD LENGTH -> ${#DOCKER_REGISTRY_PASSWORD}"
      - echo "======================"

  build:
    commands:
      - echo Building Docker image
      - docker build -t myapp:latest .

  post_build:
    commands:
      - echo Tagging and pushing image
      - docker tag myapp:latest $DOCKER_REGISTRY_USERNAME/myapp:latest
      - docker push $DOCKER_REGISTRY_USERNAME/myapp:latest
