version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm config set registry https://registry.npmjs.org/

  pre_build:
    commands:
      - echo Logging in to Docker Registry...
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - IMAGE_REPO_NAME="online-shop-app"
      - IMAGE_TAG="latest"
      - IMAGE_NAME="$DOCKER_REGISTRY_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG"

  build:
    commands:
      - echo Build started on `date`
      - echo Creating zip artifact...
      - zip -r online-shop-app.zip .
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image...
      - docker push $IMAGE_NAME
      - echo Uploading zip to S3...
      - aws s3 cp online-shop-app.zip s3://my-bucket526/online-shop-app/
      - echo Writing ECS image definition...
      - printf '[{"name":"online-shop-container","imageUri":"%s"}]' $IMAGE_NAME > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - imageDefinitions.json
