version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin

  build:
    commands:
      - echo Building Docker image
      - docker build -t myapp:latest .

  post_build:
    commands:
      - echo Pushing Docker image
      - docker tag myapp:latest <dockerhub-username>/myapp:latest
      - docker push <dockerhub-username>/myapp:latest
