version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login docker.io -u "$DOCKER_REGISTRY_USERNAME" --password-stdin

  build:
    commands:
      - echo Building Docker image
      - docker build -t myapp:latest .

  post_build:
    commands:
      - echo Tagging and pushing image
      - docker tag myapp:latest $DOCKER_REGISTRY_USERNAME/myapp:latest
      - docker push $DOCKER_REGISTRY_USERNAME/myapp:latest
